KrishnaKTechnocredits/SeleniumTechnoAug2022

src/sanket/OpenBrowser.java

Sanket_Package

---

src/SwapnilMaheshwari/Assignment2_Alert/AlertExample.java

Assignment2_SwapnilM

---

drivers/FIrstProgram.html
src/manjiri/OpenBowser.java
src/manjiri/assignment1/AutomationBrowserLaunching.java
src/manjiri/assignment1/PredefinedActions.java
src/manjiri/test_manjiri.java

Assignment1-Manjiri

---

src/adittyThakare/Assignment1.java
src/adittyThakare/PredefinedActions.java

Selenium_Assignment1_Aditty

---

src/harshalRane/FirstProg.java
src/harshalRane/base/PredefinedActions.java
src/harshalRane/pages/Page1.html
src/harshalRane/seleniumAssignments/Assignment1.java

Assignment1_Harshal

---

src/shubhamGupta/base/PredefinedActions.java
src/shubhamGupta/test/Assignment1.java
src/shubhamGupta/test/Assignment2.java

Assignment1&2_Shubham

---

src/Sohail/AlertAssignment2.java

Assignment_2_Sohail

---

src/nehanig/Assignment1.java
src/nehanig/OpenBrowser.java

Nehanig Assignment1

---

src/chaitanyaMankar/Assignment2/WindAlert.java

Assignment2_ChaitanyaM

---

src/sanket/base/MyFirstSite.html
src/sanket/base/PredefinedActions.java
src/sanket/basicprogram/Assignment1HTML.java

Assignment1_Sanket

---

src/AMohini/Assignment1/HTMLFormAssignment1.java
src/AMohini/CommonActions/PredefinedActions.java
src/AMohini/HTML/MyFirst.html
src/AMohini/OpenBrowser.java

MohiniA_Selenium_assignment1

---

src/sanket/alertprogram/Assignment2Alert.java

Assignment2_Sanket

---

src/HindaviIngle/AssignmentNo_02.java
src/HindaviIngle/Assignment_01.java

Assignment_01_02

---

src/pranjali/FirstScript.java
src/pranjali/assignment2_alerts/Alerts_Assignment2.java

Pranjali_Assignment_2

---

src/nehanig/Assignment2.java

nehanig_Assignment2

---

src/SwatiM/FirstProg.java
src/SwatiM/base/PredefinedActions.java
src/SwatiM/pages/FirstScript.html
src/SwatiM/seleniumAssignments/Assignment1.java

Assignment1_Swati

---

src/SwatiM/FirstProg.java
src/SwatiM/base/PredefinedActions.java
src/SwatiM/pages/FirstScript.html
src/SwatiM/seleniumAssignments/Assignment1.java
src/SwatiM/seleniumAssignments/Assignment2_WindAlert.java

Assignment 2 swati

---

src/nilamP/Assignment_1.java
src/nilamP/form.html

assignment1_Nilam

---

src/pujaSah/AlertDemo.java
src/pujaSah/BasicForms.java
src/pujaSah/OpenBrowser.java

Please review Selenium assignment2

---

src/akankshaVyas/Test1.java

Test akanksha vyas

---

src/akankshaVyas/Assignment1HTML.java

Assignment1_AkankshaVyas

---

src/nilamP/Assignment2.java

assignment2_Nilam

---

src/deepakPatil/Assignment1FirstCode/LoginToOwnHTMLPage.java
src/deepakPatil/Assignment2AlertHandle/AlertHandle.java
src/deepakPatil/FirstSeleniumClass.java

Created my own package and Assignment 1 and 2.

---

src/rashmiG/Assignment1_htmlpageautomation/Assignment1.java
src/rashmiG/Assignment1_htmlpageautomation/Form.html

Assignment1_RashmiG

---

src/AMohini/AlertAssign2/AlertHandel.java
src/AMohini/Assignment1/HTMLFormAssignment1.java
src/AMohini/HTML/AlertHandle.html

MohiniA_Sel_Assignment2

---

src/saroj/Assignment1.java
src/saroj/PredefinedActions.java
src/saroj/htmlFile/Assignment1.html

Selenium_Assignment1_Saroj

---

src/rashmiG/Assignment2_Alert/AlertDemo1.java
src/rashmiG/Assignment2_Alert/Assignment2.java
src/rashmiG/Base/PredefinedActions.java

Assignment2_RashmiG

---

src/apurvaBabel/Assignments/Assignment1_html.java
src/apurvaBabel/Assignments/Assignment2.java
src/apurvaBabel/OpenBrowser.java
src/apurvaBabel/Pages/DemoPage.html

Assignment1_2_ApurvaB

---

src/saroj/SeleniumAssignment2.java

Selenium Assignment2 Saroj

---

src/Titiksha/Assignment_2_Selenium.java
src/Titiksha/Assignment_2_alert_b.java

//Testcases:
//1-Open chrome browser
//2-Maximize chrome browser screen
//3-open automationkrishna webpage
//4-click basicinfo button
//5-add user name and lastname and company
//6-press submit.on submit button alert should come.
//7-on alert verify reject msg 
//8=then press accept alert
package Titiksha;
import org.openqa.selenium.Alert;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.chrome.ChromeDriver;
public class Assignment_2_Selenium  {
public static void main(String[] args) throws Exception{
System.out.println("Testcase1:Open chrome browser");
System.setProperty("webdriver.chrome.driver","drivers/chromedriver_106.exe");
WebDriver driver=new ChromeDriver();//parent child relation building
Thread.sleep(2000); …

Titiksha_Assignment_2

---

src/Titiksha/Assignment_2_Selenium.java
src/Titiksha/Assignment_2_alert_b.java
src/Titiksha/assignment_2_alert_partb.java

//Testcase1:open chrome browser
//tc2:maximize chrome browser screen
//tc3:open autiomation bykrishna webpage
//tc4:click on basic information
//tc5:give id 
//tc6:give password
//tc7:click checkbox click me out
//tc8:submit
//tc9:verify reject msg
//tc10: accept the ok button
package Titiksha;
import org.openqa.selenium.Alert;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.chrome.ChromeDriver;
public class assignment_2_alert_partb {
public static void main(String[] args) throws Exception {
System.out.println("Testcase1:open chrome browser");
System.setProperty("webdriver.chrome.driver","drivers/chromedriver_106.exe");
WebDriver driver=new ChromeDriver();
System.out.println("Testcase2:Maximize chrome browser screen"); …

Assignment 2 selenium b

---

src/harshalRane/seleniumAssignments/Assignment2AlertHandle.java

Assignment2_Harshal

---

src/Nikesh/Assignment1OpenBrowser.java
src/Nikesh/Assignment2Nikesh.java

Assignment 1  and 2

---

src/shraddhaRekhate/Assignmnent1/Assignment1.java
src/shraddhaRekhate/Assignmnent1/FirstPage.html
src/shraddhaRekhate/OpenBrowser.java
src/shraddhaRekhate/PredifinedActions.java
src/shraddhaRekhate/TestCase1.java

Assignment1_ShraddhaR

---

src/shubhamGupta/base/PredefinedActions.java
src/shubhamGupta/test/Assignment3_AlertBox.java
src/shubhamGupta/test/Assignment4_Dropdowns.java

Assignment_3_4_Shubham

---

src/vibha/Assignment1.java
src/vibha/Assignment2.java
src/vibha/PredifinedAction.java
src/vibha/pages/DemoPage.html

Assignment1_vibha

---

src/Titiksha/Assignment_2_Selenium.java
src/Titiksha/Assignment_2_alert_b.java
src/Titiksha/Assignment_3_C.java
src/Titiksha/Assignment_3_alert.java
src/Titiksha/Assignment_3_b_alert.java
src/Titiksha/assignment_2_alert_partb.java

package Titiksha;
import org.openqa.selenium.Alert;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.chrome.ChromeDriver;
public class Assignment_3_alert {
public static void main(String[] args) throws Exception {
System.out.println("Testcase1:Open chrome browser");
System.setProperty("webdriver.chrome.driver","drivers/chromedriver_106.exe");
WebDriver driver=new ChromeDriver();
driver.manage().window().maximize();
Thread.sleep(1000);
driver.get("http://automationbykrishna.com/#");
Thread.sleep(1000);
System.out.println("Testcase2:Open automationbykrishna webpage");
driver.findElement(By.id("basicelements")).click();
Thread.sleep(1000);
System.out.println("Testcase3:Open automationbykrishna webpage"); …

Assignmnet 3 titiksha

---

src/chaitanyaMankar/Assignment3/Alerts.java

Assignment3_Added

---

src/akankshaVyas/Assignment3Alert.java
src/akankshaVyas/Snippet.java
src/akankshaVyas/Test_testng.java
src/akankshaVyas/base/PredefinedActions.java

Assignment3_AkankshaVyas

---

src/deepakPatil/Assignment1FirstCode/LoginToOwnHTMLPage.java
src/deepakPatil/Assignment2AlertHandle1/AlertHandle1.java
src/deepakPatil/Assignment3AlertHandle2/AlertHandle2.java
src/deepakPatil/Assignmnet4MultiSelect/MultiSelectDropdownTest.java
src/deepakPatil/Base/PredefinedActions.java

Assignment 3 & 4. Added Base package.

---

src/sagar_Y/OpenBrowser.java
src/sagar_Y/assignment_1/Predefined.java
src/sagar_Y/assignment_1/RegistrationForm.java
src/sagar_Y/assignment_2/AlertDemo.java

Assignment_1_2_sagarY

---

src/Shruti/Assignment1.java

Assignment1_shruti

---

src/apurvaBabel/Assignments/Assignment3_DifferentAlerts.java
src/apurvaBabel/Assignments/Assignment4_MultiSelectDropdown.java
src/apurvaBabel/Assignments/Assignment5_Facebook.java
src/apurvaBabel/Files/FacebookLogin.properties
src/apurvaBabel/PredefinedActions.java
src/apurvaBabel/utils/PropertiesFileReader.java

Assignment 3
Assignment 4
Assignment 5

Assignment3_4_5_ApurvaB

---

src/nilamP/Assignment4.java

assignment4_Nilam

---

src/deepakPatil/Assignment1FirstCode/LoginToOwnHTMLPage.java
src/deepakPatil/Assignment2AlertHandle1/AlertHandle1.java
src/deepakPatil/Assignment3AlertHandle2/AlertHandle2.java
src/deepakPatil/Assignmnet4MultiSelect/MultiSelectDropdownTest.java
src/deepakPatil/assignment5PropertyFile/PropertyFileAssignment.java
src/deepakPatil/assignment5PropertyFile/SignUpDetails.properties
src/deepakPatil/base/StartupActions.java
src/deepakPatil/utils/PropertiesFileReader.java

Assignment 5. Renamed package name. Modified predefinedActions package.

---

src/saroj/SeleniumAssignment3.java
src/saroj/SeleniumAssignment4.java

Assignment4_Saroj

---

src/nilamP/assignment3/AlertDemo.java
src/nilamP/assignment3/JavaScriptAlertDemo.java
src/nilamP/assignment3/JavascriptPromptDemo.java

assignment3_Nilam

---

src/nehanig/Assignment4.java

nehanig_Assignment4

---

src/HindaviIngle/Dropdown/DropdownMethods.java
src/HindaviIngle/base/PredefinedActions.java

Assignment_04_Hindavi

---

src/Sohail/Assignment_5.java
src/Sohail/facebook.properties

Assignment_5_Sohail

---

src/shubhamGupta/Files/login.properties
src/shubhamGupta/test/Assignment5_PropertiesFilePractice.java
src/shubhamGupta/utils/PropertyFileReader.java

Assignment5_Shubham

---

src/pujaSah/DropDownTest.java
src/pujaSah/PredefinedActions.java
src/pujaSah/VerifyAlertFunctionality.java

output Assignment3:
output Assignment 4:

Please review Assignment 3 and 4

---

src/SwapnilMaheshwari/Assignment3/Alerts/JavaScriptAlertsTest.java

Assignment3_SwapnilM

---

src/sanket/alertprogram/Assignment3AlertAllTypes.java

Assignment3_Sanket

---

src/komalShrivastava/TestFile.java
src/komalShrivastava/base/PredefinedActions.java
src/komalShrivastava/testCases/TestCase1.java
src/komalShrivastava/testCases/TestCase2.java

Assignment1&2_Komal

---

src/harshalRane/seleniumAssignments/Assignment3Alerts.java

Assignment3_Harshal

---

src/Shruti/Assignment2.java
src/Shruti/base/PreDefinedActions.java

Assignment2_Shruti

---

src/Sohail/Assignment_7.java

Assignment_7_Sohail

---

src/SwatiM/base/PredefinedActions.java
src/SwatiM/seleniumAssignments/Assignment4_Dropdowns.java

Assignment_4_Swati

---

src/shubhamGupta/test/Assignment7_ActionClass.java

Assignment7_Shubham

---

src/Titiksha/Assignmnet_4_Dropdown.java

//Assignment - 4 : 29th Oct'2022
//Go to Automationbykrishna.com
//Go to Basic Element and perform below step on multi select dropdown
//how many options are there ?
//is that drodown is multi select.
//select all even numbers
//print first selected number.
//how many options are selected ?
//deselect first selected number.
//now deselect all selected option and select all non-selected options.
//print all selected option's text.
package Titiksha;
import java.util.List;
import org.openqa.selenium.By;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.support.ui.Select;
import org.testng.annotations.Test;
public class Assignmnet_4_Dropdown { …

Assignenmt_4_Titiksha

---

src/asthaSrivastava/Assignment3/VerifyAlerts.java

Assignment3_Astha

---

src/harshalRane/propertiesFile/login.properties
src/harshalRane/seleniumAssignments/Assignment5PropertiesFile.java
src/harshalRane/utils/PropertiesFileReader.java

Assignment5_Harshal

---

src/akankshaVyas/Akanksha.Properties
src/akankshaVyas/Assignment4_Select.java
src/akankshaVyas/Assignment5_Property.java
src/akankshaVyas/base/PredefinedActions.java
src/akankshaVyas/base/PropertiesFileReader.java

Assignment 4,5,some chnage

---

src/rashmiG/Assignment5_Properties_file_facebook/FacebookSignUpPage.java
src/rashmiG/Assignment5_Properties_file_facebook/signUp.properties
src/rashmiG/utils/PropertiesFileReader.java

Assignment5_RashmiG

---

src/Sohail/Iframe_Assignment_6.java
src/Sohail/PredefinedActions.java

Assignment_6_Sohail

---

src/asthaSrivastava/PredefinedActions.java
src/asthaSrivastava/TestCase1.java
src/asthaSrivastava/assignment2_Alerts/Assignment2_Alerts.java

Assignment2_Astha

---

src/sanket/propertiesfile/Assignment5_PropertiesFileTestFacebookLogin.java
src/sanket/propertiesfile/facebooklogin.properties
src/sanket/utils/ProprtiesFileReaderUtil.java

Assignment5_Sanket

---

src/harshalRane/seleniumAssignments/Assignment4MultiselectDropdown.java

Assignment4_Harshal

---

src/vibha/Assignment3.java
src/vibha/Assignment4.java
src/vibha/Assignment5.java
src/vibha/File/Facebook.properties
src/vibha/PredifinedAction.java
src/vibha/utils/PropertiesFileReader.java

Assignmemt3_5

---

src/rashmiG/Assignment3_differentTypesOfAlert/HandlingAlerts.java

Assignment3_RashmiG

---

src/rashmiG/Assignment6_iFrame_And_Switch_Window/iFrameHandling.java

Assignment6_RashmiG

---

src/akankshaVyas/Assignemnt6_iFrame.java

Assignement6

---

src/HindaviIngle/PropertyFile/FacebookSignUp.java
src/HindaviIngle/PropertyFile/userdetails

Assignment_05_Hindavi

---

src/sanket/orangeHRM_scripts/Assignment8loginOrangeHRMTestScript1.java
src/sanket/orangeHRM_scripts/orangehrm.properties

Assignment8_Sanket

---

src/deepakBorse/Assignments/Assignment4.java

src/deepakBorse/Assignments/Assignment4.java

Assignment4_DeepakB

---

src/shraddhaRekhate/Assignment2/alertAssignment.java

Assignment2_ShraddhaR

---

src/nilamP/Assignment7.java

assignment7_Nilam

---

src/nilamP/Assignment6.java

assignment6_Nilam

---

src/Sohail/Assignment_9_Sohail.java

Assignment_9_Sohail

---

src/SwapnilMaheshwari/Assignment1/PredefinedFunctions.java
src/SwapnilMaheshwari/PreDefineMethods/CommonMethods.java
src/SwapnilMaheshwari/PropertyFile/Assignment5/FacebookLogin.java
src/SwapnilMaheshwari/propertiesFile/facebookLoginCredential.properties
src/SwapnilMaheshwari/utils/PropertyFileReader.java

Assignment5_SwapnilM

---

src/deepakBorse/Assignments/Assignment3.java

Assignment3_DeepakB

---

src/AMohini/Alert/AlertHandel.java
src/AMohini/Alert/AlertHandleAssign3.java
src/AMohini/CommonActions/PredefinedActions.java
src/AMohini/DropDown/Assignment4.java
src/AMohini/FbLoginProperty/Assignment5.java
src/AMohini/FbLoginProperty/FBsignup.properties
src/AMohini/OrangeHRM/Assignment8.java
src/AMohini/OrangeHRM/LoginScript.java
src/AMohini/OrangeHRM/OrangeHRM.properties
src/AMohini/utils/PropertyFileReader.java

MohiniAssignments_3_4_5_8

---

src/Sohail/Assignment_7.java
src/Sohail/Assignment_8.java
src/Sohail/OrangeHRM.properties
src/Sohail/PredefinedActions.java
src/Sohail/PropertiyFileReader.java

Assignment_8_Sohail

---

.classpath
src/saroj/SeleniumAssignment6.java

Selenium assignment6 saroj

---

src/shubhamGupta/Files/OrangeHrm.properties
src/shubhamGupta/Files/OrangeHrmMyInfo.properties
src/shubhamGupta/base/PredefinedActions.java
src/shubhamGupta/test/Assignment8_OrageHRMTest1.java

Assignment8_Shubham

---

src/rashmiG/Assignment7_Actions_class_methods/HandlingElementsUsingDoubleclickDragdropMousehover.java

Assignment7_RashmiG

---

src/sanket/actionsclassdemo/Assignment7ActionsClassDoubleClickAction.java
src/sanket/actionsclassdemo/Assignment7ActionsClassDragNDrop.java
src/sanket/actionsclassdemo/Assignment7ActionsClassMouseHover.java

**Script 1: Drag & Drop Result:**
**Script 2: Double click on element**
**Script 3: Mouse hover**

Assignment7_Sanket

---

src/deepakPatil/assignment4MultiSelect/MultiSelectDropdownTest.java
src/deepakPatil/assignment6Frames/FrameCode1.java
src/deepakPatil/assignment6Frames/FrameCode2.java
src/deepakPatil/base/StartupActions.java

Assignment6_DeepakP

---

src/nehanig/Assignment6.java
src/nehanig/Assignment6_1.java
src/nehanig/Assignment6_2.java

Nehanig assignment6

---

src/nilamP/assignment5/Assignment5.java
src/nilamP/assignment5/PropertiesReadFile.java
src/nilamP/assignment5/facebook.properties

assignment5_Nilam

---

src/apurvaBabel/Assignments/Assignment6_IFrame.java
src/apurvaBabel/Assignments/Assignment7_DragDrop_DoubleClick_MouseHover.java

Assignment 6 IFrame1
Assignment 6 IFrame3
Assignment 7 Drag and drop
Assignment 7 Double click
Assignment 7 Mouse hover

Assignment6_7_ApurvaB

---

src/gauravSahu/Assignment/Assignment1.java
src/gauravSahu/Assignment/Assignment2.java
src/gauravSahu/Assignment/Assignment3.java
src/gauravSahu/Assignment/Assignment4.java
src/gauravSahu/Assignment/Assignment5.java
src/gauravSahu/Assignment/Assignment6.java
src/gauravSahu/Assignment/Assignment6A.java
src/gauravSahu/Assignment/Assignment7.java
src/gauravSahu/Assignment/Assignment7A.java
src/gauravSahu/Assignment/Assignment7B.java
src/gauravSahu/Assignment/Assignment8A.java
src/gauravSahu/Assignment/Assignment9.java
src/gauravSahu/InitialActions.java
src/gauravSahu/Practice/Practice1.java
src/gauravSahu/Practice/Practice2.java
src/gauravSahu/Practice/Practice3.java
src/gauravSahu/propertiesFile/OrangeHRMInfoDetails.properties
src/gauravSahu/propertiesFile/OrangeHRMLoginDetails.properties
src/gauravSahu/propertiesFile/propertyFile.properties

Assignment 1 
Assignment 2
Assignment 3
Assignment 4
Assignment 6
Assignment 7
Assignment 8

Assigment1to8

---

src/harshalRane/base/PredefinedActions.java
src/harshalRane/seleniumAssignments/Assignment6_iFrame.java

Assignment6_Harshal

---

src/SwapnilMaheshwari/Assignment8/OrangeHRMLogin/OrangeHRMLogin.java
src/SwapnilMaheshwari/PreDefineMethods/CommonMethods.java

Selenium_Assignment8

---

src/sanket/orangeHRM_scripts/Assignment10OrangeHRMTestScript3.java
src/sanket/orangeHRM_scripts/Assignment10OrangeHRMTestScript4.java

Script 3 Result : 
Employee Details
Script 4 Result  :

Assignment10_Sanket

---

src/HindaviIngle/OrangeHrmScenario/Assignment_08_LoginNPersonalDetails.java
src/HindaviIngle/OrangeHrmScenario/Assignment_09_UploadADoc.java
src/HindaviIngle/PropertyFile/OrangeHrmDetails

Assignment_08_Hindavi

---

src/nilamP/orangeHRM/PropertiesReadFile.java
src/nilamP/orangeHRM/TestCase1.java
src/nilamP/orangeHRM/personalInfo.properties

assignment8_Nilam

---

.classpath
src/vibha/Assignment6.java
src/vibha/Assignment6to10/Assignment6_IFrame.java
src/vibha/Assignment6to10/Assignment7.java

Assignment6and7

---

src/apurvaBabel/OrangeHRMScripts/Assignment10_TC_3.java
src/apurvaBabel/OrangeHRMScripts/Assignment10_TC_4.java
src/apurvaBabel/OrangeHRMScripts/Assignment8_TestCaseID1.java
src/apurvaBabel/OrangeHRMScripts/Assignment9_TestCaseID6_RobotClass.java
src/apurvaBabel/OrangeHRMScripts/OrangeHRMLogin.properties

Assignment 8
Assignment 9
Assignment 10_TC3
Assignment 10_TC4

Assignment8_9_10_ApurvaB

---

src/asthaSrivastava/PredefinedActionsLaunchUrl.java
src/asthaSrivastava/assignment4/DropDownMethodOperations.java

Assignment4_Astha

---

src/HindaviIngle/DragDropDoubleClickMouseHover/Assignment_07_DoubleClick.java
src/HindaviIngle/DragDropDoubleClickMouseHover/Assignment_07_DragDrop.java
src/HindaviIngle/DragDropDoubleClickMouseHover/Assignment_07_MouseHover.java

Assignmnet_07_hindavi

---

src/nehanig/Assignment7.java
src/nehanig/Assignment7_DoubleClick.java
src/nehanig/Assignment7_DragDrop.java

nehanig_Assignment7

---

src/HindaviIngle/iframe/Assignment_06.java

Assignment_06_hindavi

---

src/nehanig/Assignment8.java
src/nehanig/OrangeHRM.properties

nehani_Assignment8

---

src/Titiksha_selenium/Filename.property
src/Titiksha_selenium/Login_Page.java
src/Titiksha_selenium/PredefinedActions.java
src/Titiksha_selenium/PropertyFileReader.java
src/Titiksha_selenium/organgeHRM.properties

Titiksha_goel_Assignment8_OrangeHRM

---

src/gauravSahu/Assignment/Assignment10.java
src/gauravSahu/Assignment/Assignment9.java
src/gauravSahu/propertiesFile/OrangeHRMInfoDetails.properties

Assignment9&10_with propertiesfile

---

src/asthaSrivastava/assignment7/DoubleClick.java
src/asthaSrivastava/assignment7/DragAndDrop.java
src/asthaSrivastava/assignment7/MouseHover.java

Assignment7_Astha

---

src/deepakPatil/assignment8LoginOrangeHRM/LoginOrangeHRM.java
src/deepakPatil/assignment8LoginOrangeHRM/OrangeHRMDetails.properties

Assignment8_DeepakP

---

src/deepakBorse/Assignment7DragdropDclick/Assignment7Doubleclick.java
src/deepakBorse/Assignment7DragdropDclick/Assignment7Dragdrop.java
src/deepakBorse/Assignment7DragdropDclick/Assignment7Mousehover.java

Script 1 - snapshot : 
Script 2- Snapshot:
Script 3- Snapshot:

Assignment8_DeepakB

---

src/akankshaVyas/OrangeHRM/Assignment10_TC3.java
src/akankshaVyas/OrangeHRM/Assignment9_Upload.java

Assignment 9 & 10

---

src/nehanig/Assignment3.java

nehanig_Assignment3

---

src/pujaSah/HtmlForms/BlankLinkPractice.html
src/pujaSah/HtmlForms/BrokenLink.html
src/pujaSah/HtmlForms/Display_And_Enabled.html
src/pujaSah/HtmlForms/MultiWindow.html
src/pujaSah/OrangeHRMLogin/FileUpload.java
src/pujaSah/OrangeHRMLogin/LoginScript.java
src/pujaSah/OrangeHRMLogin/OrangeHRMLoginDetails.properties

Assignment 8 output:
Assignment 9 output:

Please review Assignment 8 and 9

---

src/nilamP/orangeHRM/TestCase2.java

assignment9_Nilam

---

src/vibha/Assignments/Assignment10.java
src/vibha/Assignments/Assignment8.java
src/vibha/Assignments/Assignment9.java
src/vibha/Assignments/OrangeHRMLogin.properties
src/vibha/PredifinedAction.java

Assignment8To10

---

src/harshalRane/propertiesFile/OrangeHRM.properties
src/harshalRane/seleniumAssignments/Assignment8StandaloneTC1.java

Assignment8_Harshal

---

src/asthaSrivastava/Files/login.properties
src/asthaSrivastava/Pages/FirstHtmlPage.html
src/asthaSrivastava/PredefinedActions.java
src/asthaSrivastava/assignment5/FacebookFillPageUsingPropFile.java
src/asthaSrivastava/utils/PropertiesFileReader.java

Assignment5_Astha

---

src/deepakPatil/assignment7ActionsClass/DoubleClick.java
src/deepakPatil/assignment7ActionsClass/DragAndDrop.java
src/deepakPatil/assignment7ActionsClass/MouseHover.java

Assignment7_DeepakP

---

src/adittyThakare/Assignment2.java

Selenium_Assignment2_Aditty

---

src/deepakPatil/assignment9RobotClass/OrangeHRMDetails.properties
src/deepakPatil/assignment9RobotClass/RobotClassTS6.java

Assignment9_DeepakP

---

src/SwatiM/seleniumAssignments/Assignment6_iFrame.java

Assignment_6_Swati

---

src/rashmiG/orangeHrm/Assignment9fileupload.java
src/rashmiG/orangeHrm/orangeHrm.properties

Assignment9_RashmiG

---

src/nehanig/Assignment9.java
src/nehanig/OrangeHRMCredentials

nehanig_Assignment9TC

---

src/komalShrivastava/actionClass/DragDropAndDoubleClick.java
src/komalShrivastava/actionClass/MouseHoverFlipkartPractice.java

Assignment 7:
Script 1:
Script 2:
Script 3:

 Assignment7_Komal

---

src/komalShrivastava/orangeHRMScripts/TestScript1.java
src/komalShrivastava/properties/login.properties

Assignment8_Komal

---

src/komalShrivastava/robotClass/FileUpload.java

Assignment9_Komal

---

src/SwapnilMaheshwar/Assign10/OrangeHRMAbout_TS3.java

Assignment 10 TS3

---

src/komalShrivastava/testCases/OrangeHRMAssignment10.java

Assignment 10 :
TC_3
1. Launch your oranage HRM URL
2. User Login with valid credential
3. Verify User profile is displayed
4. Mouse Hover on Profile and Click on setting icon on profile
5. Verify user menu total 2 options displayed
6. Click on About
7. Verify Employee is more than 0
8. Verify the company details  fields are getting displayed on information alert (Company Name, Version, Employees, Users & Renewal on)
9. Click on OK button on popup.
TC_4
1. Launch your oranage HRM URL
2. User Login with valid credential
3. User click on Employee Management tab
4. Click on My Info tab
5. Verify user Personal info displayed
6. Click on ""Salary""
7. Check the payable (CTC) amount is non-zero

Assignment10_Komal

---

src/asthaSrivastava/assignment9/OrangeHRMLogin.properties
src/asthaSrivastava/assignment9/UploadAndVerifyDocumentTC2.java

Added Assignment9

---

src/shraddhaRekhate/PredifinedActions.java
src/shraddhaRekhate/orangehrm/OrangeHrm.java
src/shraddhaRekhate/orangehrm/orangehrm.properties

Assignment8_Shraddha

---

src/asthaSrivastava/assignment10/OrangeHRMTC3.properties
src/asthaSrivastava/assignment10/TC3.java
src/asthaSrivastava/assignment10/TC4_Salary.java

Assignment10_Astha
